### PR TITLE
Registration page update

### PR DESCRIPTION
**Pull request by RealRedRobot**
## Type of Change

- [ ] Bug Fix (Non-breaking change which resolves an issue)
- [x] New Feature/Enhancement (Non-breaking change which add functionality)
- [ ] Breaking Change (Fix or enhancement that causes existing functionality to change)
- [ ] Release Activity

### CODE REVIEW

**Comment by Dwooll94** [comment]
I think there may be some unintended changes here look through the changes carefully. I think you mau have forgotten to update your local from this repo before starting.

**Comment by Dwooll94** [comment]
Also check the app preview generated by this PR, I can't get to your new page.

**Comment by casheridan** [comment]
Yeah, I was wondering why the preview wasn't picking up the latest changes because it definetly should be reflecting them. Looking at the workflow file and the example they have [here](https://github.com/marketplace/actions/deploy-to-firebase-hosting#deploy-to-a-new-preview-channel-for-every-pr), there is some discrepancy with how the pr preview workflow file looks. I can make some changes to fix the discrepancy and hopefully it will fix the issue of the preview not picking up his changes.

**Comment by casheridan** [comment]
Sorry, might be opening and closing to test the new workflow. Just as a heads up for the notifs.

**Comment by casheridan** [comment]
Ah, I figured out why it won't show up on the preview and why the new workflow is failing. Any PR that is issued from a fork will not have access to the github repo secrets (found [here](https://github.com/v8/v8.dev/issues/485#:~:text=GitHub%20doesn%27t%20supply%20secret%20values%20to%20the%20action%20when%20a%20PR%20is%20made%20from%20a%20fork.%20I%27ve%20been%20meaning%20to%20document%20this%20(FirebaseExtended/action%2Dhosting%2Ddeploy%2317)%2C%20sorry%20it%20wasn%27t%20clear.)). The previous workflow allowed the preview to be built but didn't look at the fork as it also didn't have access to see the fork. @RealRedRobot @Dwooll94 So any changes in the future need to be made to a branch instead of a fork.

**Pull request closed without merging**
